spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator: true
        low-case-service-id: true


server:
  port: 80

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
